my_polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),   # http://localhost:8000/polls/
    path('<int:aaa>/', views.detail, name='detail'),   # http://localhost:8000/polls/2
    path('<int:bbb>/vote/', views.vote, name='vote'),
]

polls/models.py
from django.db import models

class Question(models.Model):
    # 자동으로 생성되는 id는 PK, 1씩 자동증가(autoincrement)
    # id = models.IntegerField()
    question_text = models.CharField('투표질문제목', max_length = 200)
    pub_date = models.DateTimeField('투표생성날짜')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField('투표보기문구', max_length = 30)
    votes = models.IntegerField('투표수', default = 0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from polls.models import Question

# view의 function이 하는 일은 request를 받아서 결과 template html
# 을 이용해서 결과파일을 만들어 내는 일.
def index(request):
    # database에서 투표질문의 목록을 가져올 거예요!
    # 원래는 문자열로 표현되야 하는데 .. ORM을 사용하다 보니 .. 각 레코드가
    # Question 클래스의 객체로 표현.
    my_list = Question.objects.all().order_by('-pub_date')
    context = {'question_list':my_list}
    return render(request, 'index.html', context)

def detail(request, aaa):
    tmp = get_object_or_404(Question, pk=aaa)
    context = {"question":tmp}
    return render(request, 'detail.html', context)

def vote(request, bbb):
    # URL로 넘어온 데이터(bbb)는 Question 객체의 id가 넘어왔어요!
    question = get_object_or_404(Question, pk=bbb)
    # request header 안에 form에서 선택한 데이터가 포함되서 전달되고
    # 이것을 추출하기 위해서 request.POST["choice"]를 사용

    selected_choice = question.choice_set.get(pk=request.POST["choice"])

    selected_choice.votes += 1
    selected_choice.save()

    # result.html에서 현재 투표항목에 대한 각 항목들의 투표현황을 출력!!
    context = {'question':question}
    return render(request, 'result.html', context)

polls/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
     <!-- action = http://localhost:8000/polls/1/vote/ -->
     <h1>{{ question.question_text }}</h1>
     <form action = "{% url 'polls:vote' question.id %}" method = "post">
     {% csrf_token %}
         {%for choice in question.choice_set.all %}
           <input type = "radio" name = "choice"
                  id = "choice{{ forloop.counter }}"
                  value = "{{ choice.id }}">
         <label for = "choice{{ forloop.counter }}">
             {{ choice.choice_text }}
         </label>
         {% endfor %}
         <br><br>
         <input type = "submit" value = "투표">
     </form>

</body>
</html>

polls/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
     <h1>투표목록입니다.</h1>
     <ul>
     {% for question in question_list %}
         <!-- polls/1 -->
         <!-- http://localhost:8000/polls/polls/1 -->
         <!-- http://localhost:8000/polls/1 -->
         <li><a href = "/polls/{{ question.id }}">{{ question.question_text}}</a></li>
     {% endfor %}
     </ul>

</body>
</html>

polls/templates/result.html
<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset = "UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
           <li>{{choice.choice_text}} - {{choice.votes}} votes </li>
        {% endfor %}
    </ul>

</body>
</html>